# pre-defined variables
server:
  port: 8083

# pre-defined variables
spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1:5432/yahoo_finace"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    # Hibernate ddl auto (create, create-drop, validate, update, none)
